name: Metrics
on:
  schedule: [{cron: "0 17 * * *"}]
  workflow_dispatch:
  # push: {branches: ["master", "main"]}
jobs:
  github-metrics:
    runs-on: ubuntu-latest
    steps:
      - name: General
        uses: lowlighter/metrics@latest
        with:
          filename: general.svg
          token: ${{ secrets.METRICS_TOKEN }}
          committer_gist: ${{ secrets.GIST }}
          output_action: gist
          config_timezone: Asia/Bangkok
          repositories_forks: yes

          base: header, activity, repositories
          base_indepth: yes

          plugin_introduction: yes
          plugin_introduction_title: yes

          plugin_isocalendar: yes
          plugin_isocalendar_duration: half-year

          plugin_languages: yes
          plugin_languages_limit: 16
          # plugin_languages_sections: most-used, recently-used
          plugin_languages_sections: most-used
          # plugin_languages_indepth: yes
          # plugin_languages_details: lines, bytes-size, percentage
          plugin_languages_details: bytes-size, percentage

          plugin_topics: yes
          plugin_topics_limit: 0
          plugin_topics_mode: icons

          plugin_notable: yes

          # plugin_activity: yes
          # plugin_activity_days: 14
          # plugin_activity_filter: all
          # plugin_activity_limit: 5
          # plugin_activity_load: 300
          # plugin_activity_visibility: all

          plugin_followup: yes
          plugin_followup_sections: repositories

          plugin_habits: yes
          plugin_habits_days: 14
          plugin_habits_facts: yes
          plugin_habits_from: 200
          plugin_habits_trim: yes

          plugin_lines: yes
          plugin_traffic: yes

          # config_order: base.header, introduction, base.activity, base.repositories, isocalendar, languages, followup, habits, notable, topics

      - name: Achievements
        uses: stalomeow/metrics@projects-v2
        with:
          filename: achievementsV2.svg
          token: ${{ secrets.METRICS_TOKEN }}
          committer_gist: ${{ secrets.GIST }}
          output_action: gist
          base: ""
          plugin_achievements: yes

      - name: Social
        uses: lowlighter/metrics@latest
        with:
          filename: social.svg
          token: ${{ secrets.METRICS_TOKEN }}
          committer_gist: ${{ secrets.GIST }}
          output_action: gist
          base: ""
          plugin_fortune: yes
          plugin_steam: yes
          plugin_steam_token: ${{ secrets.STEAM_TOKEN }}
          plugin_steam_user: "76561199037473758"
